openapi: 3.0.0
info:
  title: Catalog
  version: v0.1.0
  description: |
    This is the REST API documentation for the [Catalog](https://github.com/vmwarecloudadvocacy/catalogsvc) Service app of the [ACME Fitness Shop](https://github.com/vmwarecloudadvocacy/acme_fitness_demo).
  contact:
    name: VMware Cloud Advocacy team
    url: 'https://github.com/vmwarecloudadvocacy'
  license:
    name: MIT
    url: 'https://github.com/vmwarecloudadvocacy/catalogsvc/blob/master/LICENSE'
servers:
  - url: 'http://localhost:8082'
paths:
  /liveness:
    get:
      summary: Liveness
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      version:
                        type: string
                      servicename:
                        type: string
                  status:
                    type: integer
              examples:
                sample: {}
      operationId: get_liveness
      description: The liveness operation returns the current status and version of the server
  '/products/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get Product Details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      shortDescription:
                        type: string
                      imageUrl1:
                        type: string
                      imageUrl2:
                        type: string
                      imageUrl3:
                        type: string
                      price:
                        type: number
                      tags:
                        type: array
                        items:
                          type: string
                  status:
                    type: integer
              examples:
                sample:
                  value:
                    data:
                      id: 5c61f497e5fdadefe84ff9b9
                      name: Yoga Mat
                      shortDescription: Limited Edition Mat
                      description: Limited edition yoga mat
                      imageUrl1: /static/images/yogamat_square.jpg
                      imageUrl2: /static/images/yogamat_square.jpg
                      imageUrl3: /static/images/bottle_square.jpg
                      price: 62.5
                      tags:
                        - mat
                    status: 200
      description: Returns details about a specific product id
      operationId: get_product_details
  '/static/images/{imageName}':
    parameters:
      - type: string
        name: imageName
        in: path
        required: true
    get:
      summary: Get Image
      tags: []
      responses: {}
      description: Retrieve specific image
  /products:
    get:
      summary: Get All Products
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        shortDescription:
                          type: string
                        description:
                          type: string
                        imageUrl1:
                          type: string
                        imageUrl2:
                          type: string
                        imageUrl3:
                          type: string
                        price:
                          type: number
                        tags:
                          type: array
                          items:
                            type: string
              examples:
                sample:
                  value:
                    data:
                      - id: 5c61f497e5fdadefe84ff9b9
                        name: Yoga Mat
                        shortDescription: Limited Edition Mat
                        description: Limited edition yoga mat
                        imageUrl1: /static/images/yogamat_square.jpg
                        imageUrl2: /static/images/yogamat_thumb2.jpg
                        imageUrl3: /static/images/yogamat_thumb3.jpg
                        price: 62.5
                        tags:
                          - mat
                      - id: 5c61f497e5fdadefe84ff9ba
                        name: Water Bottle
                        shortDescription: Best water bottle ever
                        description: 'For all those athletes out there, a perfect bottle to enrich you'
                        imageUrl1: /static/images/bottle_square.jpg
                        imageUrl2: /static/images/bottle_thumb2.jpg
                        imageUrl3: /static/images/bottle_thumb3.jpg
                        price: 34.99
                        tags:
                          - bottle
      description: Returns a list of all catalog items
      operationId: get_all_products
    post:
      summary: Post New Product
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  resourceId:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      shortDescription:
                        type: string
                      description:
                        type: string
                      imageUrl1:
                        type: string
                      imageUrl2:
                        type: string
                      imageUrl3:
                        type: string
                      price:
                        type: number
                      tags:
                        type: array
                        items:
                          type: string
                  status:
                    type: integer
              examples:
                sample:
                  value:
                    message: 'Product created successfully!'
                    resourceId:
                      id: 5c61f8f81d41c8e94ecaf25f
                      name: Tracker
                      shortDescription: Limited Edition Tracker
                      description: Limited edition Tracker with longer description
                      imageUrl1: /static/images/tracker_square.jpg
                      imageUrl2: /static/images/tracker_thumb2.jpg
                      imageUrl3: /static/images/tracker_thumb3.jpg
                      price: 149.99
                      tags:
                        - tracker
                    status: 201
      description: Create a new product item
      operationId: post_product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                shortDescription:
                  type: string
                description:
                  type: string
                imageUrl1:
                  type: string
                imageUrl2:
                  type: string
                imageUrl3:
                  type: string
                price:
                  type: number
                tags:
                  type: array
                  items:
                    type: string
            examples:
              sample:
                value:
                  name: Tracker
                  shortDescription: Limited Edition Tracker
                  description: Limited edition Tracker with longer description
                  imageurl1: /static/images/tracker_square.jpg
                  imageurl2: /static/images/tracker_thumb2.jpg
                  imageurl3: /static/images/tracker_thumb3.jpg
                  price: 149.99
                  tags:
                    - tracker
        description: Create product payload
components:
  schemas: {}
